#!/bin/bash

echo "📋 Instructions for creating manual TDR Nova preset:"
echo ""
echo "1. Open Logic Pro"
echo "2. Create new project with audio track"  
echo "3. Add TDR Nova to the track"
echo "4. Make OBVIOUS changes:"
echo "   - Turn on Band 1 (make it active)"
echo "   - Set Band 1 gain to maximum or minimum"
echo "   - Change Band 1 frequency to an extreme setting"
echo "   - Change bypass to ON, then back to OFF"
echo "5. Click TDR Nova's preset menu"
echo "6. Choose 'Save As...' or similar"
echo "7. Name it 'ManualReference'"
echo "8. Save it"
echo ""
echo "Then run this to find it:"
echo "find ~/Library/Audio/Presets -name '*ManualReference*' -o -name '*Manual*'"
echo ""
echo "The preset should be in:"
echo "~/Library/Audio/Presets/Tokyo Dawn Labs/TDR Nova/"
